### PR TITLE
Update MainActivity.java

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by otakuchiyan** [comment]
This label may be used at next version.

**Comment by mimi89999** [comment]
screenshot_2015-10-07-20-09-07

**Comment by mimi89999** [comment]
I wanted to remove the "System properties" text.

**Comment by otakuchiyan** [comment]
I may add a another text about the firewall rules on future, so the text should to be preseved.
If I decided not to add a new text, I will remove it.

**Comment by mimi89999** [comment]
What about my other PR?

**Pull request closed without merging**
